# Generated by Django 4.1.2 on 2024-02-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomuser_member_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
