services:
  web:
    image: teamglade/tg-app:alpha-1.3
# use expose with nginx and use ports to directly access to gunicorn in container
    expose:
      - 8000
#    ports:
#      - "8000:8000"
# uncomment this if docker file doesn't have command to run server
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 teamglade.wsgi:application
    volumes:
      - static_files:/app/static
      - media_files:/app/media
# synchronize app code inside and outside container (including .env file)
#    volumes:
#      - .:/app
    env_file: .env
#    environment:
#      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
  db:
    image: postgres:15.7-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  nginx:
    image: teamglade/tg-nginx:alpha-1.6
    volumes:
#      - static_files:/home/app/static
      - static_files:/usr/share/nginx/html/static
      - media_files:/usr/share/nginx/html/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
  media_files:
