services:
  web:
    image: tg_app:alpha-1.0
    ports:
      - "8000:8000"
# uncomment this if docker file doesn't have command to run server
    command: python manage.py runserver 0.0.0.0:8000
# synchronize app code inside and outside container (including .env file)
#    volumes:
#      - .:/app
    env_file: .env
#    environment:
#      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
  db:
    image: postgres:15.7-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
