services:
  web:
    image: tg-app3
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
#    environment:
#      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
  db:
    image: postgres:15.7-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
